gui:
  showBottomLine: false
  scrollHeight: 20
  sidePanelWidth: 0.2
promptToReturnFromSubprocess: false
keybinding:
  universal:
    nextTab: L
    prevTab: H
    nextBlock-alt: J
    prevBlock-alt: K
    scrollLeft: h
    scrollRight: l
git:
  pagers:
    - pager: delta -s --paging=never
      externalDiffCommand: difft --color=always
